### PR TITLE
Added source map handling

### PR DESCRIPTION
**Pull request by null-patcher**

### CODE REVIEW

**Review by tomasz-oponowicz — CHANGES_REQUESTED** [review]
@GosuTeacher Thanks for your contribution. Would you be so kind to add tests?

**Comment by null-patcher** [comment]
Sorry for the update and reply. Hope everything is ok. If there are missing cases, please let me know. Other pointers are welcome, also. Thanks!

**Review by tomasz-oponowicz — APPROVED** [review]
lgtm

**Comment by tomasz-oponowicz** [comment]
@GosuTeacher Your PR has been released as 1.2.0.

**Pull request merged**
